### PR TITLE
Add a travis.ci file

### PR DESCRIPTION
**Pull request by momoneko**
# Ready State and Ticket
**Ready**

# Details
We're not running any CI on ef-open since it's a public repo and anybody can botch our Jenkins pipelines. Why not make us of Travis, which allows free CI for open source project?

We need to setup a Travis.ci account, but the rest is quite simple.

e.g: https://travis-ci.com/momoneko/ef-open

### CODE REVIEW

**Comment by vfangellation** [comment]
We might need some discussion on this one.

**Comment by vfangellation** [comment]
@stidwell-ellation do we want to go down this path or not yet?

**Comment by vfangellation** [comment]
I'd say we close this PR since we don't seem to be doing travis anytime soon.

**Comment by vfangellation** [comment]
Also I have a ticket to create a CI for ef-open in Jenkins.

**Comment by momoneko** [comment]
We shouldn't be doing ci for a public project on Jenkins. That basically allows anybody to run code on our machine.

**Pull request merged**
