### PR TITLE
Git tagging as version management

### PR DESCRIPTION
**Pull request by triplepoint**
## Ready State
**Ready**

## Synopsis
Added `versioneer` as a manager for ef-open's versions.  Now, versions are defined by git tags instead of being hard-coded into the code itself.
https://github.com/warner/python-versioneer

This gives us a CI event to look for, to automatically release new versions when new tags are created, and avoids that follow up commit just to bump the release version.

See the included README changes for details on how it works.

Once this is landed, we can tag that resulting commit to master as `0.1.3` which will be the same version that's currently specified in the current codebase.

[OPS-10780](https://ellation.atlassian.net/browse/OPS-10780)

## Changelog
See above

## Dependencies
Versioneer was added, but the way it functions is essentially vendoring in a copy of itself, so there are no additional package requirements.

### CODE REVIEW

**Comment by dlutsch** [comment]
Is dropping in the versioneer.py into root the best method here? Any reason why we couldn't just pip install versioneer on jenkins?

**Comment by triplepoint** [comment]
> Is dropping in the versioneer.py into root the best method here? Any reason why we couldn't just pip install versioneer on jenkins?

This stuff gets touchy, because setup.py is calling these functions, so they 100% have to be present before ef-open's setup.py is ever called.  So there's a chicken and egg issue, where setup.py has to be called to find out what its dependencies are, but one of its dependencies is necessary for setup.py to function.

It's worth noting that setup.py and versioneer.py don't end up packaged into the binary .whl releases, so they don't end up present for most installs.  They are packaged with the source sdist packages.

Finally, Versioneer's readme has Dire Portents about screwing around with the root directory's structure.  This isn't exactly about the location of versioneer.py, but it makes me wonder what would break if we went moving it. https://github.com/warner/python-versioneer#subprojects.  

If it's a problem, though, we could try moving it to a subdirectory somewhere and see what happens.

**Comment by dlutsch** [comment]
Cool, not a sticking point. Let's give this a shot.

**Comment by triplepoint** [comment]
Ok cool, Merged, then I did:
```
git tag -a 0.1.3 -m "tagging 0.1.3"
git push --tags
```
Now, when I check the project version I get:
```
 $ python setup.py version
running version
keywords are unexpanded, not using
got version from VCS {'version': '0.1.3', 'full-revisionid': 'f511a969d571accef0507498b67629102ce79d8e', 'dirty': False, 'error': None, 'date': '2018-10-15T15:56:21-0700'}
Version: 0.1.3
 full-revisionid: f511a969d571accef0507498b67629102ce79d8e
 dirty: False
 date: 2018-10-15T15:56:21-0700
```

And when I do:
```
python2 setup.py sdist bdist_wheel
```

I get:
```
$ ls -l dist
total 264
-rw-r--r--  1 jhanson  staff  64153 Oct 15 15:59 ef-open-0.1.3.tar.gz
-rw-r--r--  1 jhanson  staff  67452 Oct 15 15:59 ef_open-0.1.3-py2-none-any.whl
```

**Pull request merged**
