### PR TITLE
Cxops 2921 ef_aws_resolver unit tests

### PR DESCRIPTION
**Pull request by vfangellation**
## Ready State
**Ready**

## Synopsis
Modified and added unit tests for ef_aws_resolver.py Again, these tests are assumptions on how the boto3 library will respond at the time of writing of these tests and can give false positives if the boto3 library or AWS changes their responses to the API calls.
[CXOPS-2921](https://ellation.atlassian.net/browse/CXOPS-2921)

Note: I expect the test cases to be butchered if things don't look right.

## Changelog
Modified and added unit tests for ef_aws_resolver.py

## Dependencies
None

## Linked PRs
None

## Testing
Some of the tests fail due to code or logic errors found in the source code during testing.
The 5 tests fail for the following reasons:

1. test_acm_certificate_arn_old_matching_certificate_has_no_issued_date fails because the  acm_certificate_arn generates a datetime.datetime object set to the IssuedAt field instead of a float value.
1. test_acm_certificate_arn_target_certificate_has_no_issued_date fails because the target certificate does not have IssuedAt date while the old certificate with the same domain does. This is either a logic error or some tribal knowledge on why this logic was chosen.
1. test_lookup_invalid_input fails because lookup does not know how to handle a None input
1. test_route53_private_hosted_zone_id_is_truncated fails because route53_private_hosted_zone_id is looking for a NextMarker field instead of NextHostedZoneId and NextDNSName if the list is truncated
1. test_route53_public_hosted_zone_id_is_truncated fails for the same reason as test_route53_private_hosted_zone_id_is_truncated

Coverage is currently 93% of ef_aws_resolver.py
```
(venv-2.7) vfang-mlt:ef-open vfang$ pytest tests/unit_tests/test_ef_aws_resolver.py --cov ef_aws_resolver -v --cov-report term-missing
==================================================== test session starts ====================================================
platform darwin -- Python 2.7.10, pytest-3.1.2, py-1.4.34, pluggy-0.4.0 -- /Users/vfang/venv-2.7/bin/python
cachedir: .cache
rootdir: /Users/vfang/workspace/ef-open, inifile:
plugins: cov-2.5.1
collected 51 items 

tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_acm_certificate_arn PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_acm_certificate_arn_bad_input PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_acm_certificate_arn_multiple_matching_certificates PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_acm_certificate_arn_no_certificates PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_acm_certificate_arn_old_matching_certificate_has_no_issued_date FAILED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_acm_certificate_arn_target_certificate_has_no_issued_date FAILED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_cloudfront_domain_name PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_cloudfront_domain_name_is_truncated PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_cloudfront_domain_name_no_match PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_cloudfront_origin_access_identity_oai_canonical_user_id PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_cloudfront_origin_access_identity_oai_canonical_user_id_is_truncated PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_cloudfront_origin_access_identity_oai_canonical_user_id_no_match PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_cloudfront_origin_access_identity_oai_id PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_cloudfront_origin_access_identity_oai_id_is_truncated PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_cloudfront_origin_access_identity_oai_id_no_match PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_ec2_elasticip_elasticip_id PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_ec2_elasticip_elasticip_id_bad_input PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_ec2_elasticip_elasticip_ipaddress PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_ec2_elasticip_elasticip_ipaddress_bad_input PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_ec2_eni_eni_id PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_ec2_eni_eni_id_no_match PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_ec2_route_table_main_route_table_id PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_ec2_route_table_main_route_table_id_no_single_match PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_ec2_security_group_security_group_id PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_ec2_security_group_security_group_id_no_match PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_ec2_subnet_subnet_id PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_ec2_subnet_subnet_id_no_match PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_ec2_vpc_availabilityzones PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_ec2_vpc_availabilityzones_no_match PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_ec2_vpc_availabilityzones_no_vpc_id PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_ec2_vpc_cidrblock PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_ec2_vpc_cidrblock_no_match PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_ec2_vpc_subnets PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_ec2_vpc_subnets_no_match PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_ec2_vpc_vpc_id PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_ec2_vpc_vpc_id_none PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_lookup_invalid_input FAILED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_route53_private_hosted_zone_id PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_route53_private_hosted_zone_id_is_truncated FAILED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_route53_private_hosted_zone_id_malformed_domain_name PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_route53_private_hosted_zone_id_no_match PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_route53_public_hosted_zone_id PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_route53_public_hosted_zone_id_is_truncated FAILED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_route53_public_hosted_zone_id_malformed_domain_name PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_route53_public_hosted_zone_id_no_match PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_waf_rule_id PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_waf_rule_id_more_rules_than_limit PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_waf_rule_id_no_match PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_waf_web_acl_id PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_waf_web_acl_id_more_web_acls_than_limit PASSED
tests/unit_tests/test_ef_aws_resolver.py::TestEFAwsResolver::test_waf_web_acl_id_no_match PASSED

---------- coverage: platform darwin, python 2.7.10-final-0 ----------
Name                     Stmts   Miss  Cover   Missing
------------------------------------------------------
src/ef_aws_resolver.py     234     16    93%   92, 110-111, 137, 141, 174-175, 230, 331, 357, 378, 400, 425, 450, 466, 504


========================================================= FAILURES ==========================================================
__________________ TestEFAwsResolver.test_acm_certificate_arn_old_matching_certificate_has_no_issued_date ___________________

self = <tests.unit_tests.test_ef_aws_resolver.TestEFAwsResolver testMethod=test_acm_certificate_arn_old_matching_certificate_has_no_issued_date>

    def test_acm_certificate_arn_old_matching_certificate_has_no_issued_date(self):
      """
        Tests acm_certificate_arn to see if it returns correct target certificate arn when the older
        matching certificate has no matching DateIssued.
    
        Returns:
          None
    
        Raises:
          AssertionError if any of the assert checks fail
        """
      target_certificate_arn = "arn:aws:acm:us-west-2:111000:certificate/target_cert"
      target_domain_name = "second.com"
      lookup_token = "acm:certificate-arn,us-west-2/" + target_domain_name
      mock_acm_client = Mock(name="Mock ACM Client")
      mock_acm_client.list_certificates.return_value = {
        "CertificateSummaryList": [
          {
            "CertificateArn": "arn:aws:acm:us-west-2:111000:certificate/not_target_cert",
            "DomainName": "first.com"
          },
          {
            "CertificateArn": target_certificate_arn,
            "DomainName": target_domain_name
          },
          {
            "CertificateArn": target_certificate_arn,
            "DomainName": target_domain_name
          }
        ]
      }
      old_certificate = {
        "Certificate": {
          "DomainName": target_domain_name,
          "CertificateArn": "arn:aws:acm:us-west-2:111000:certificate/older_target_cert"
        }
      }
      target_certificate = {
        "Certificate": {
          "IssuedAt": 1472845485.0,
          "DomainName": target_domain_name,
          "CertificateArn": target_certificate_arn
        }
      }
      mock_acm_client.describe_certificate.side_effect = [old_certificate, target_certificate]
      self._clients["SESSION"].client.return_value = mock_acm_client
      ef_aws_resolver = EFAwsResolver(self._clients)
>     result_certificate_arn = ef_aws_resolver.lookup(lookup_token)

tests/unit_tests/test_ef_aws_resolver.py:260: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
src/ef_aws_resolver.py:468: in lookup
    return self.acm_certificate_arn(*kv[1:])
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <ef_aws_resolver.EFAwsResolver object at 0x10e552990>, lookup = 'us-west-2/second.com', default = None

    def acm_certificate_arn(self, lookup, default=None):
      """
        Args:
          lookup: region/domain on the certificate to be looked up
          default: the optional value to return if lookup failed; returns None if not set
        Returns:
          ARN of a certificate with status "Issued" for the region/domain, if found, or default/None if no match
          If more than one "Issued" certificate matches the region/domain:
            - if any matching cert was issued by Amazon, returns ARN of certificate with most recent IssuedAt timestamp
            - if no certs were issued by Amazon, returns ARN of an arbitrary matching certificate
            - certificates issued by Amazon take precedence over certificates not issued by Amazon
        """
      # @todo: Only searches the first 100 certificates in the account
    
      try:
        # This a region-specific client, so we'll make a new client in the right place using existing SESSION
        region_name, domain_name = lookup.split("/")
        acm_client = EFAwsResolver.__CLIENTS["SESSION"].client(service_name="acm", region_name=region_name)
        response = acm_client.list_certificates(
          CertificateStatuses=['ISSUED'],
          MaxItems=100
        )
      except Exception:
        return default
      # No certificates
      if len(response["CertificateSummaryList"]) < 1:
        return default
      # One or more certificates - find cert with latest IssuedAt date or an arbitrary cert if none are dated
      best_match_cert = None
      for cert_handle in response["CertificateSummaryList"]:
        if cert_handle["DomainName"] == domain_name:
          cert = acm_client.describe_certificate(CertificateArn=cert_handle["CertificateArn"])["Certificate"]
          if best_match_cert is None:
            best_match_cert = cert
            # Patch up cert if there is no IssuedAt (i.e. cert was not issued by Amazon)
            if not best_match_cert.has_key("IssuedAt"):
              best_match_cert[u"IssuedAt"] = datetime.datetime(1970, 1, 1, 0, 0)
>         elif cert.has_key("IssuedAt") and cert["IssuedAt"] > best_match_cert["IssuedAt"]:
E         TypeError: can't compare datetime.datetime to float

src/ef_aws_resolver.py:88: TypeError
_____________________ TestEFAwsResolver.test_acm_certificate_arn_target_certificate_has_no_issued_date ______________________

self = <tests.unit_tests.test_ef_aws_resolver.TestEFAwsResolver testMethod=test_acm_certificate_arn_target_certificate_has_no_issued_date>

    def test_acm_certificate_arn_target_certificate_has_no_issued_date(self):
      """
        Tests acm_certificate_arn to see if target certificate is returned even when it has no date issued.
    
        Returns:
          None
    
        Raises:
          AssertionError if any of the assert checks fail
        """
      target_certificate_arn = "arn:aws:acm:us-west-2:111000:certificate/target_cert"
      target_domain_name = "second.com"
      lookup_token = "acm:certificate-arn,us-west-2/" + target_domain_name
      mock_acm_client = Mock(name="Mock ACM Client")
      mock_acm_client.list_certificates.return_value = {
        "CertificateSummaryList": [
          {
            "CertificateArn": "arn:aws:acm:us-west-2:111000:certificate/not_target_cert",
            "DomainName": "first.com"
          },
          {
            "CertificateArn": target_certificate_arn,
            "DomainName": target_domain_name
          },
          {
            "CertificateArn": target_certificate_arn,
            "DomainName": target_domain_name
          }
        ]
      }
      old_certificate = {
        "Certificate": {
          "IssuedAt": 1472845000.0,
          "DomainName": target_domain_name,
          "CertificateArn": "arn:aws:acm:us-west-2:111000:certificate/older_target_cert"
        }
      }
      target_certificate = {
        "Certificate": {
          "DomainName": target_domain_name,
          "CertificateArn": target_certificate_arn
        }
      }
      mock_acm_client.describe_certificate.side_effect = [old_certificate, target_certificate]
      self._clients["SESSION"].client.return_value = mock_acm_client
      ef_aws_resolver = EFAwsResolver(self._clients)
      result_certificate_arn = ef_aws_resolver.lookup(lookup_token)
>     self.assertEquals(result_certificate_arn, target_certificate_arn)
E     AssertionError: 'arn:aws:acm:us-west-2:111000:certificate/older_target_cert' != 'arn:aws:acm:us-west-2:111000:certificate/target_cert'

tests/unit_tests/test_ef_aws_resolver.py:310: AssertionError
________________________________________ TestEFAwsResolver.test_lookup_invalid_input ________________________________________

self = <tests.unit_tests.test_ef_aws_resolver.TestEFAwsResolver testMethod=test_lookup_invalid_input>

    def test_lookup_invalid_input(self):
      """
        Tests lookup with all invalid inputs
    
        NOTE: Don't need to create valid input test cases since all the other unit tests do that with each different
        lookup.
    
        Returns:
          None
    
        Raises:
          AssertionError if any of the assert checks fail
        """
      ef_aws_resolver = EFAwsResolver(self._clients)
    
>     result = ef_aws_resolver.lookup(None)

tests/unit_tests/test_ef_aws_resolver.py:1790: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <ef_aws_resolver.EFAwsResolver object at 0x10e6e8250>, token = None

    def lookup(self, token):
      try:
>       kv = token.split(",")
E       AttributeError: 'NoneType' object has no attribute 'split'

src/ef_aws_resolver.py:464: AttributeError
____________________________ TestEFAwsResolver.test_route53_private_hosted_zone_id_is_truncated _____________________________

self = <tests.unit_tests.test_ef_aws_resolver.TestEFAwsResolver testMethod=test_route53_private_hosted_zone_id_is_truncated>

    def test_route53_private_hosted_zone_id_is_truncated(self):
      """
        Tests route53_private_hosted_zone_id to see if it returns the correct hosted zone id if the results are
        truncated based on domain name given
    
        Returns:
          None
        """
      target_hosted_zone_id = "112233"
      target_hosted_zone_name = "my_domain.com."
      first_hosted_zones_by_name_response = {
        "HostedZones": [
          {
            "Config": {
              "PrivateZone": True
            },
            "Id": "/hostedzone/1Z2Y3X",
            "Name": "other_domain.com."
          },
          {
            "Config": {
              "PrivateZone": False
            },
            "Id": "/hostedzone/B1C1D1",
            "Name": "other_domain.com."
          }
        ],
        "IsTruncated": True,
        "NextHostedZoneId": "aabbcc"
      }
      second_hosted_zones_by_name_response = {
        "HostedZones": [
          {
            "Config": {
              "PrivateZone": False
            },
            "Id": "/hostedzone/AABBCC",
            "Name": target_hosted_zone_name
          },
          {
            "Config": {
              "PrivateZone": True
            },
            "Id": "/hostedzone/" + target_hosted_zone_id,
            "Name": target_hosted_zone_name
          }
        ],
        "IsTruncated": False
      }
      self._clients["route53"].list_hosted_zones_by_name.side_effect = [first_hosted_zones_by_name_response,
                                                                        second_hosted_zones_by_name_response]
      ef_aws_resolver = EFAwsResolver(self._clients)
>     result = ef_aws_resolver.lookup("route53:private-hosted-zone-id," + target_hosted_zone_name)

tests/unit_tests/test_ef_aws_resolver.py:1230: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
src/ef_aws_resolver.py:496: in lookup
    return self.route53_private_hosted_zone_id(*kv[1:])
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <ef_aws_resolver.EFAwsResolver object at 0x10e6d5590>, lookup = 'my_domain.com.', default = None

    def route53_private_hosted_zone_id(self, lookup, default=None):
      """
        Args:
          lookup: The zone name to look up. Must end with "."
          default: the optional value to return if lookup failed; returns None if not set
        Returns:
          the ID of the private hosted zone for the 'lookup' domain, or default/None if no match found
        """
      list_limit = "100"
      # enforce terminal '.' in name, otherwise we could get a partial match of the incorrect zones
      if lookup[-1] != '.':
        return default
      hosted_zones = EFAwsResolver.__CLIENTS["route53"].list_hosted_zones_by_name(DNSName=lookup, MaxItems=list_limit)
      # Return if the account has no HostedZones
      if not hosted_zones.has_key("HostedZones"):
        return default
      while True:
        for hosted_zone in hosted_zones["HostedZones"]:
          if lookup == hosted_zone["Name"] and hosted_zone["Config"]["PrivateZone"]:
            return hosted_zone["Id"].split("/")[2]
        if hosted_zones["IsTruncated"]:
          hosted_zones = EFAwsResolver.__CLIENTS["route53"].list_hosted_zones_by_name(
>           MaxItems=list_limit, Marker=hosted_zones["NextMarker"])
E         KeyError: 'NextMarker'

src/ef_aws_resolver.py:364: KeyError
_____________________________ TestEFAwsResolver.test_route53_public_hosted_zone_id_is_truncated _____________________________

self = <tests.unit_tests.test_ef_aws_resolver.TestEFAwsResolver testMethod=test_route53_public_hosted_zone_id_is_truncated>

    def test_route53_public_hosted_zone_id_is_truncated(self):
      """
        Tests route53_public_hosted_zone_id to see if it returns the correct hosted zone id for when the results
        returned need to be truncated based on given domain name
    
        Returns:
          None
    
        Raises:
          AssertionError if any of the assert checks fail
        """
      target_hosted_zone_id = "112233"
      target_hosted_zone_name = "my_domain.com."
      first_hosted_zones_by_name_response = {
        "HostedZones": [
          {
            "Config": {
              "PrivateZone": True
            },
            "Id": "/hostedzone/1Z2Y3X",
            "Name": "other_domain.com."
          },
          {
            "Config": {
              "PrivateZone": False
            },
            "Id": "/hostedzone/B1C1D1",
            "Name": "other_domain.com."
          }
        ],
        "IsTruncated": True,
        "NextHostedZoneId": "aabbcc"
      }
      second_hosted_zones_by_name_response = {
        "HostedZones": [
          {
            "Config": {
              "PrivateZone": True
            },
            "Id": "/hostedzone/AABBCC",
            "Name": target_hosted_zone_name
          },
          {
            "Config": {
              "PrivateZone": False
            },
            "Id": "/hostedzone/" + target_hosted_zone_id,
            "Name": target_hosted_zone_name
          }
        ],
        "IsTruncated": False
      }
      self._clients["route53"].list_hosted_zones_by_name.side_effect = [first_hosted_zones_by_name_response,
                                                                        second_hosted_zones_by_name_response]
      ef_aws_resolver = EFAwsResolver(self._clients)
>     result = ef_aws_resolver.lookup("route53:public-hosted-zone-id," + target_hosted_zone_name)

tests/unit_tests/test_ef_aws_resolver.py:1054: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
src/ef_aws_resolver.py:498: in lookup
    return self.route53_public_hosted_zone_id(*kv[1:])
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <ef_aws_resolver.EFAwsResolver object at 0x10e6e8b10>, lookup = 'my_domain.com.', default = None

    def route53_public_hosted_zone_id(self, lookup, default=None):
      """
        Args:
          lookup: The zone name to look up. Must end with "."
          default: the optional value to return if lookup failed; returns None if not set
        Returns:
          the ID of the public hosted zone for the 'lookup' domain, or default/None if no match found
        """
      list_limit = "100"
      # enforce terminal '.' in name, otherwise we could get a partial match of the incorrect zones
      if lookup[-1] != '.':
        return default
      hosted_zones = EFAwsResolver.__CLIENTS["route53"].list_hosted_zones_by_name(DNSName=lookup, MaxItems=list_limit)
      # Return if the account has no HostedZones
      if not hosted_zones.has_key("HostedZones"):
        return default
      while True:
        for hosted_zone in hosted_zones["HostedZones"]:
          if lookup == hosted_zone["Name"] and not hosted_zone["Config"]["PrivateZone"]:
            return hosted_zone["Id"].split("/")[2]
        if hosted_zones["IsTruncated"]:
          hosted_zones = EFAwsResolver.__CLIENTS["route53"].list_hosted_zones_by_name(
>           MaxItems=list_limit, Marker=hosted_zones["NextMarker"])
E         KeyError: 'NextMarker'

src/ef_aws_resolver.py:338: KeyError
============================================ 5 failed, 46 passed in 0.56 seconds ============================================
```

### CODE REVIEW

**Comment by theJWong** [comment]
Can we fix the merge conflict?

**Comment by vfangellation** [comment]
Will fix merge conflict but don't look at this PR for now, some things Dan pointed out that I want to try out and see before asking everyone to review this.

**Comment by theJWong** [comment]
Did we ever add documentation on contributing to add unit-test cases?

**Comment by vfangellation** [comment]
There is a JIRA page https://ellation.atlassian.net/wiki/spaces/DEVOPS/pages/89564596/Python+Unit+Testing
I'll take another look at writing test cases section to see if it's enough

**Comment by dlutsch** [comment]
@theJWong @vfangellation 
While we're in the process of defining our testing standards I think it would be worthwhile to take a crack at doing this testing with moto rather than straight mock. Vince has written a frankly impressive amount of testing code, however because we are creating all of these response objects manually our unit test code is now more than 3x larger than the code base it's covering. While I have no doubt about the functionality, the size and scope of this can make it onerous to contribute to and maintain (especially important if we plan to actual grain traction as an open source project). Doing this with moto could potentially take these tests down from 1800 lines to a few hundred. 

Thoughts?

**Comment by theJWong** [comment]
I'm all for maintainability and reducing LOC. We can do this as a two phase approach. We can commit this code for now and then rewrite all of these unit-test cases using moto. When writing this using moto, we can make sure that there is parity between the two by seeing if the moto test cases passes just as these current test cases passes.

**Comment by dlutsch** [comment]
Sounds good to me. +1

**Comment by theJWong** [comment]
+1

**Comment by vfangellation** [comment]
Sorry small quick review, this is all that changed in test_ef_aws_resolver.py 

line 21 - 26

# For local application imports, context_paths must be first despite lexicon ordering
import context_paths
from ef_aws_resolver import EFAwsResolver
from ef_config import EFConfig
from ef_context import EFContext
from ef_utils import fail, http_get_metadata, whereami

**Comment by dlutsch** [comment]
+1

**Pull request merged**
